### ISSUE TITLE
[BREAKING]: incomplete distribution on npm

### ISSUE THREAD

**Issue by BlitzJB** [piyushgarg-dev/react-razorpay#6]
npm distribution is incomplete. only has below files
![image](https://github.com/piyushgarg-dev/react-razorpay/assets/88381529/6eb3876f-c0ed-499a-ad6b-41a7d9975cd8)

see https://www.npmjs.com/package/react-razorpay?activeTab=code

since merge of #4 

@piyushgarg-dev (Tagged as breaking)

**Comment by piyushgarg-dev** [comment]
Please install react-razorpay@2.0.1

**Comment by BlitzJB** [comment]
Resolved!

Unbelievable speed
